### ISSUE TITLE
How to create Status Library & use in application

### ISSUE THREAD

**Issue by fsmanpk** [shahzadmasud/objava42web#1]
Dear Sir,

Sorry to disturb you. Please guide how to add status library and use the resource of status error in our application. please guide step wise.

thanks
faisal

**Comment by shahzadmasud** [comment]
You mean to ask custom messages of Status messages. Please elaborate your question a little more.

**Comment by fsmanpk** [comment]
I would like to clear again how to add these library in our projects. kindly guide the method step wise to add them in our web project.

thanks
Faisal

**Comment by shahzadmasud** [comment]
http://objava42.blogspot.com/2015/08/introduction-to-struts-framework-using.html

**Comment by shahzadmasud** [comment]
http://objava42.blogspot.com/2015/08/introduction-to-struts-framework-using.html

SM
