### ISSUE TITLE
How we create tlds

### ISSUE THREAD

**Issue by fsmanpk** [shahzadmasud/objava42web#3]
Dear Sir,

please guide how we create tlds files. Please guide step wise.

regards

**Comment by shahzadmasud** [comment]
There are two answers, 

a. TLD (Tag Library Descriptor), this file is kinda header file for all custom tags, which would be created manually. If you are using NetBeans, then you'll not get more trouble while if you are using eclipse; then you might have to create them from scratch. 

b. If you are asking in perspective of struts, then these files would be same for all struts projects so copying those files directly to WEB-INF would work.
